---
title: "BZAN 542-CSGO"
author: "Group 8"
date: "2022-12-12"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Loads in the data and packages needed.
```{r}
#Change the working directory to your own.
setwd("C:/Users/liana/Downloads/archive")

#Loads in the required packages
library(tidyverse)
library(dplyr)
library(reshape2)

# Read in and combine the two .csv files containing the by-event damage data
csgo_data <- rbind(read.csv("esea_master_dmg_demos.part1.csv"), 
             read.csv("esea_master_dmg_demos.part2.csv"))

# Read in the win data for the matches
csgo_win_data <- rbind(read.csv("esea_meta_demos.part1.csv"), read.csv("esea_meta_demos.part2.csv")) 

```

Finds the column names and how the games are grouped in the dataset.
```{r}

colnames(csgo_data)

files_names <- unique(csgo_data$file) #each file is a separate ESEA match with all of its associated data
```



Creates unique identities for each player in each match that stays through each round so we can document hp.
```{r}
player_round_map <- csgo_data %>%
                    select(file, round, vic_side, vic_id) %>%
                    distinct() %>% #eliminates repeats of the exact same row where rows are identical
                    group_by(file, round, vic_side) %>% #groups by the match, round, then victim side that was shot
                    mutate(pnumber = row_number()) %>% #makes a column called pnumber which is th row number
                    mutate(player_id = paste0(vic_side, pnumber)) %>% #combines the two string names together to make the names for the players
                    ungroup() %>% #ungroups items to delete stuff
                    select(-pnumber, -vic_side) %>% #deletes pnumber and vic_side columns because we have player_id now
                    spread(player_id, vic_id) %>% 
                    select(file,
                           round,
                           CounterTerrorist1,
                           CounterTerrorist2,
                           CounterTerrorist3,
                           CounterTerrorist4,
                           CounterTerrorist5,
                           Terrorist1,
                           Terrorist2,
                           Terrorist3,
                           Terrorist4,
                           Terrorist5)
```


Creates a table which documents the damage taken by each player for each round of each match
```{r}
tagged_dmg_data <- csgo_data %>%
                   left_join(player_round_map, by=c('file','round')) %>% #combines the new table with full table data by round=file
                   rowwise() %>%
                   mutate(CounterTerrorist1Dmg = if(vic_id %in% CounterTerrorist1) -hp_dmg else 0, #Sorts into each column who the dmg is taken by
                           CounterTerrorist2Dmg = if(vic_id %in% CounterTerrorist2) -hp_dmg else 0,
                           CounterTerrorist3Dmg = if(vic_id %in% CounterTerrorist3) -hp_dmg else 0,
                           CounterTerrorist4Dmg = if(vic_id %in% CounterTerrorist4) -hp_dmg else 0,
                           CounterTerrorist5Dmg = if(vic_id %in% CounterTerrorist5) -hp_dmg else 0,
                           Terrorist1Dmg = if(vic_id %in% Terrorist1) -hp_dmg else 0,
                           Terrorist2Dmg = if(vic_id %in% Terrorist2) -hp_dmg else 0,
                           Terrorist3Dmg = if(vic_id %in% Terrorist3) -hp_dmg else 0,
                           Terrorist4Dmg = if(vic_id %in% Terrorist4) -hp_dmg else 0,
                           Terrorist5Dmg = if(vic_id %in% Terrorist5) -hp_dmg else 0)
```

